-- MySQL Script generated by MySQL Workbench
-- Seg 13 Jun 2016 17:58:34 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema deploy
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema deploy
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `deploy` DEFAULT CHARACTER SET utf8 ;
USE `deploy` ;

-- -----------------------------------------------------
-- Table `deploy`.`grupo_servidor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deploy`.`grupo_servidor` (
  `id_grupo_servidor` INT NOT NULL AUTO_INCREMENT,
  `nome_grupo_servidor` VARCHAR(45) NOT NULL,
  `descricao_grupo_servidor` TEXT NULL,
  `status_grupo_servidor` VARCHAR(2) NULL,
  `data_cadastro_grupo_servidor` DATE NULL,
  PRIMARY KEY (`id_grupo_servidor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `deploy`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deploy`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `id_grupo_servidor` INT NOT NULL,
  `nome_usuario` VARCHAR(100) NOT NULL,
  `login_usuario` VARCHAR(45) NOT NULL,
  `senha_usuario` VARCHAR(100) NOT NULL,
  `status_usuario` VARCHAR(2) NULL,
  `data_cadastro_usuario` DATE NULL,
  `obs_usuario` TEXT NULL,
  `nivel_usuario` INT NOT NULL,
  `funcao_usuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_usuario`, `id_grupo_servidor`),
  INDEX `fk_usuario_grupo_servidor1_idx` (`id_grupo_servidor` ASC),
  CONSTRAINT `fk_usuario_grupo_servidor1`
    FOREIGN KEY (`id_grupo_servidor`)
    REFERENCES `deploy`.`grupo_servidor` (`id_grupo_servidor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `deploy`.`log_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deploy`.`log_usuario` (
  `id_log_usuario` INT NOT NULL AUTO_INCREMENT,
  `id_usuario_log` INT NOT NULL,
  `id_grupo_log` INT NOT NULL,
  `data` DATE NULL,
  `obs_log_usuario` TEXT NULL,
  `ip_acesso_log` VARCHAR(45) NULL,
  PRIMARY KEY (`id_log_usuario`, `id_usuario_log`, `id_grupo_log`),
  INDEX `fk_log_usuario_usuario1_idx` (`id_usuario_log` ASC, `id_grupo_log` ASC),
  CONSTRAINT `fk_log_usuario_usuario1`
    FOREIGN KEY (`id_usuario_log` , `id_grupo_log`)
    REFERENCES `deploy`.`usuario` (`id_usuario` , `id_grupo_servidor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `deploy`.`servidor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deploy`.`servidor` (
  `id_servidor` INT NOT NULL AUTO_INCREMENT,
  `id_grupo_servidor` INT NOT NULL,
  `nome_servidor` VARCHAR(60) NOT NULL,
  `ip_servidor` VARCHAR(45) NOT NULL,
  `obs_servidor` TEXT NULL,
  `data_cadastro_servidor` DATE NULL,
  `status_servidor` INT NULL,
  PRIMARY KEY (`id_servidor`, `id_grupo_servidor`),
  INDEX `fk_servidor_grupo_servidor1_idx` (`id_grupo_servidor` ASC),
  CONSTRAINT `fk_servidor_grupo_servidor1`
    FOREIGN KEY (`id_grupo_servidor`)
    REFERENCES `deploy`.`grupo_servidor` (`id_grupo_servidor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `deploy`.`usuarios_servidor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deploy`.`usuarios_servidor` (
  `id_usuarios_servidor` INT NOT NULL AUTO_INCREMENT,
  `id_servidor` INT NOT NULL,
  `nome_usuarios_servidor` VARCHAR(50) NOT NULL,
  `path_usuarios_servidor` VARCHAR(45) NULL,
  `data_usuarios_servidor` DATE NULL,
  `status_usuario_servidor` VARCHAR(2) NULL,
  PRIMARY KEY (`id_usuarios_servidor`, `id_servidor`),
  INDEX `fk_usuarios_servidor_servidor1_idx` (`id_servidor` ASC),
  CONSTRAINT `fk_usuarios_servidor_servidor1`
    FOREIGN KEY (`id_servidor`)
    REFERENCES `deploy`.`servidor` (`id_servidor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `deploy`.`sistema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deploy`.`sistema` (
  `id_sistema` INT NOT NULL AUTO_INCREMENT,
  `id_usuarios_servidor` INT NOT NULL,
  `id_servidor` INT NOT NULL,
  `nome_sistema` VARCHAR(50) NOT NULL,
  `path_sistema` VARCHAR(100) NOT NULL,
  `data_cadastro_sistema` DATE NULL,
  `status_sistema` VARCHAR(2) NULL,
  PRIMARY KEY (`id_sistema`, `id_usuarios_servidor`, `id_servidor`),
  INDEX `fk_sistema_usuarios_servidor1_idx` (`id_usuarios_servidor` ASC, `id_servidor` ASC),
  CONSTRAINT `fk_sistema_usuarios_servidor1`
    FOREIGN KEY (`id_usuarios_servidor` , `id_servidor`)
    REFERENCES `deploy`.`usuarios_servidor` (`id_usuarios_servidor` , `id_servidor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `deploy`.`file_deploy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deploy`.`file_deploy` (
  `id_file_deploy` INT NOT NULL AUTO_INCREMENT,
  `id_usuario_file_deploy` INT NOT NULL,
  `id_sistema` INT NOT NULL,
  `id_usuarios_servidor` INT NOT NULL,
  `id_servidor` INT NOT NULL,
  `nome_file_deploy` VARCHAR(45) NULL,
  `data_file_deploy` DATE NULL,
  `status_file_deploy` VARCHAR(2) NULL,
  `obs_file_deploy` TEXT NULL,
  PRIMARY KEY (`id_file_deploy`, `id_usuario_file_deploy`, `id_sistema`, `id_usuarios_servidor`, `id_servidor`),
  INDEX `fk_file_deploy_usuario1_idx` (`id_usuario_file_deploy` ASC),
  INDEX `fk_file_deploy_sistema1_idx` (`id_sistema` ASC, `id_usuarios_servidor` ASC, `id_servidor` ASC),
  CONSTRAINT `fk_file_deploy_usuario1`
    FOREIGN KEY (`id_usuario_file_deploy`)
    REFERENCES `deploy`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_file_deploy_sistema1`
    FOREIGN KEY (`id_sistema` , `id_usuarios_servidor` , `id_servidor`)
    REFERENCES `deploy`.`sistema` (`id_sistema` , `id_usuarios_servidor` , `id_servidor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
